version: "3.8"
services:
  db:
    image: mysql:8.0
    healthcheck:
      test: "exit 0"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: Cash_Flow
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
volumes:
  db_data:
